id = "setinox-theme"
name = "Setinox"
version = "0.2.0"
schema_version = 1
authors = ["https://github.com/infectiious"]
description = "A Zed theme based on the Seti UI color palette."
repository = "https://github.com/infectiious/setinox.zed"
